hash-format = "sha256"

[[files]]
file = "config/biome_replacer.properties"
hash = "c68ae499f7056b03d1321289edd8850d37f29ea57651bd6e9af05a4ae833f12a"

[[files]]
file = "config/kiwi-client.yaml"
hash = "ee880f0ac378ab3d6e4a83fc1b00cd12fd329a3846a025b5bc2896354ac17cac"

[[files]]
file = "config/kiwi-common.yaml"
hash = "48bca49edf4ee6b363fe56139eec197f36399fb87e73b71443959bdb8598a955"

[[files]]
file = "config/snowrealmagic-client.yaml"
hash = "34909564dc66fb400f716437577c349965144e46febfb432a388aed3b0fe81e9"

[[files]]
file = "config/snowrealmagic-common.yaml"
hash = "e9cbb9b8671d14207841fb4bc6aace9a171840c3a5acdbcbcd22691439cc9da1"

[[files]]
file = "datapacks/jolly_remove_biomes/pack.mcmeta"
hash = "218553daec530831d97520c179bf64105c24cd7698601bbbf38f7cf02b5c2e2c"

[[files]]
file = "mods/amendments.pw.toml"
hash = "61ab7794e676f45410312efe39c2cc6edf5835f4d7fa5ab685be0c0e4b78f984"
metafile = true

[[files]]
file = "mods/asyncparticles.pw.toml"
hash = "4f20967ee66eb96cbcfaa63bea9d3424ac45b7db414c9a491f31c86012f34fb5"
metafile = true

[[files]]
file = "mods/cloth-config.pw.toml"
hash = "75181b55e0407d1fca1e2f346c6501f919f5109545990ddfb66db9cd1b771f8a"
metafile = true

[[files]]
file = "mods/create.pw.toml"
hash = "d6043c928c34ce1f4ada544a49193f95c281665cf88d4931e73370ea02870bed"
metafile = true

[[files]]
file = "mods/glitchcore.pw.toml"
hash = "dbd756dd9bb17e6ecebcf2d7052a67a2da1c7dd378bc2089bc154916080fe031"
metafile = true

[[files]]
file = "mods/kiwi.pw.toml"
hash = "caa948011054593b7452cfc4fa7276ff61748770285fd6b7ee5078816eed043b"
metafile = true

[[files]]
file = "mods/lithium.pw.toml"
hash = "7b8e8af83e8583adc91b2d859e5355f1bd0516a346d2584b8b01c004467d18af"
metafile = true

[[files]]
file = "mods/moonlight.pw.toml"
hash = "b2062526afe3f3c55ad508247fc25246f0b3087ac21890ff29fea2b521e289cd"
metafile = true

[[files]]
file = "mods/particle-rain.pw.toml"
hash = "95886f73121a490ab360dac8e99f260fb0346048e86475c658ed44ddd399f09e"
metafile = true

[[files]]
file = "mods/paxi.pw.toml"
hash = "215d597764d5c5db89e700fc3495b72dc0a7f09c975de19dc8c580bde3469a5e"
metafile = true

[[files]]
file = "mods/quick-pack.pw.toml"
hash = "884325ab8ea09fc82883a3e27c340c3e978c167420977e89166061b31338a490"
metafile = true

[[files]]
file = "mods/snow-real-magic.pw.toml"
hash = "a1deef8071fb83a13df63c289576813b82f0687eebda9b48b7667620d5d45103"
metafile = true

[[files]]
file = "mods/snow-sniffer.pw.toml"
hash = "87540c0d6ab0668d93a31b77eb794c76acee411475365a148eb1225e029d5a0d"
metafile = true

[[files]]
file = "mods/snow-under-trees.pw.toml"
hash = "82aedef3c457ffe51e27a4153aaf73ef7c073b87059a021495af487e41ed2e99"
metafile = true

[[files]]
file = "mods/sodium.pw.toml"
hash = "0281ed9713f3141bdac363056a791845510e14761ea65b4b2813cf96d664b20a"
metafile = true

[[files]]
file = "mods/supplementaries.pw.toml"
hash = "2632cdb92a41c1c8fe4eb6d4a76deb9febb62c9e62cb9d91ad9794e42829f7c8"
metafile = true

[[files]]
file = "mods/yacl.pw.toml"
hash = "9a89a97f142873b9ab62d2c7c807ac22e6f16c828282052b416a6f3f7f785a48"
metafile = true

[[files]]
file = "mods/yungs-api.pw.toml"
hash = "d9c0c9209bac0b693af2a7c1e47ffb28d366bad19c91df31dc6d345fa75250a1"
metafile = true
