hash-format = "sha256"

[[files]]
file = "changelog/1.4.0.md"
hash = "241623c2b86c060969033258b0ed606c0e20146fc719159901a2dd6e59446d62"

[[files]]
file = "config/biome_replacer.properties"
hash = "0bc8ecf3ec129589d05d7344db1f82cab87d9e6c39bb02d528c3488a6be35163"

[[files]]
file = "config/bridgingmod.json"
hash = "8a270a285af132b0ac31e8b9a60a43f659fd48cb90d9fb6fa54a1ae6e20c0fd5"

[[files]]
file = "config/entityculling.json"
hash = "9617b1f0d9a5bcef2e3d23397814bed0e7d29e19de75374b2177502f1f3a2446"

[[files]]
file = "config/kiwi-client.yaml"
hash = "ee880f0ac378ab3d6e4a83fc1b00cd12fd329a3846a025b5bc2896354ac17cac"

[[files]]
file = "config/kiwi-common.yaml"
hash = "48bca49edf4ee6b363fe56139eec197f36399fb87e73b71443959bdb8598a955"

[[files]]
file = "config/moonlight-common.toml"
hash = "fbce75f9cd9258e0726a2ee1aed8f156bdc7ba04902a7434fa6292be954b1082"

[[files]]
file = "config/opticmanager.json"
hash = "399961f4ebc36bb1363d4289e1f0a6be0ce080329ecce51d10bf3c046bcd7921"

[[files]]
file = "config/sereneseasons/fertility.toml"
hash = "722f7545a5a592f0aed25ae8dd0a4f53f7abaf0bb53da96417d87e9096e75631"

[[files]]
file = "config/sereneseasons/seasons.toml"
hash = "5b297f30ddde7d07d490a8f8aa80bfb8bfa9d616455b8b33a8658e58a37ed0ce"

[[files]]
file = "config/snowrealmagic-common.yaml"
hash = "e87604d500f557c4cfebc3e29e0419b299b14af4cdaf1659f6dc81ab136bb1c3"

[[files]]
file = "config/snowy-common.toml"
hash = "c6f00ae04b25d65a11b2dc5d28e39914b42e0f622b1551c9e05fc69cc3788873"

[[files]]
file = "config/yosbr/config/raised.json"
hash = "012d6e3c8dce5fdb9b54cb15b3e34812b127dc280b28e86fc016d342dbb9e4c0"

[[files]]
file = "config/yosbr/config/snowrealmagic-client.yaml"
hash = "34909564dc66fb400f716437577c349965144e46febfb432a388aed3b0fe81e9"

[[files]]
file = "datapacks/biome_tweaks/pack.mcmeta"
hash = "c2a30294c8e87ca241775d322a1c30f6f73256a6057c9f3848f318ec0293a163"

[[files]]
file = "datapacks/no-yungs-advancements/pack.mcmeta"
hash = "cf645c4a9b468b8e3242c86de9f7d41d870307855163854e345a6ee678ecae15"

[[files]]
file = "datapacks/recipe_tweaks/data/jolly_recipe_tweaks/recipe/chain.json"
hash = "bdcd4f6968ad90c05690727d5a4341a508039c022297ca30e9d8947b159eb54f"

[[files]]
file = "datapacks/recipe_tweaks/data/jolly_recipe_tweaks/recipe/fried_egg.json"
hash = "fca3f501121a86eb4e59905de187f51c6b3e5ad1e25fca3bed66ab82c85b1a83"

[[files]]
file = "datapacks/recipe_tweaks/data/jolly_recipe_tweaks/recipe/fried_egg_from_campfire_cooking.json"
hash = "7dd2634b23296383e3aaa9e0a0f1e9344f1cd93d71b5fefa6d7aedb48cf5089d"

[[files]]
file = "datapacks/recipe_tweaks/data/jolly_recipe_tweaks/recipe/fried_egg_from_smoking.json"
hash = "0a274c020ba6326c9784fb931fb3150233af77e7a79e9ae4bdd6297bcb2c4747"

[[files]]
file = "datapacks/recipe_tweaks/pack.mcmeta"
hash = "50ae42b53f9fa94144823b0b77115bc7fc5810e26d1976e8bae2b5dc9fb1ee9a"

[[files]]
file = "mods/amendments.pw.toml"
hash = "ed544632f7925bd625ac4297ae797be46a2ae0fcaad9eecf893cd78093eda4d0"
metafile = true

[[files]]
file = "mods/appleskin.pw.toml"
hash = "3213c881d019cd8f952f738c10d5a950ee52ff0084750b81f656a58a4a78515d"
metafile = true

[[files]]
file = "mods/architectury-api.pw.toml"
hash = "ea336d25c3e21ef168aec20e1ea470c96949ad29632646ee8e8ab0d74b4bbfc9"
metafile = true

[[files]]
file = "mods/asyncparticles.pw.toml"
hash = "4f20967ee66eb96cbcfaa63bea9d3424ac45b7db414c9a491f31c86012f34fb5"
metafile = true

[[files]]
file = "mods/badoptimizations.pw.toml"
hash = "dd56ff2bcc4253d1d70c08333632743fb56cdc4cf5518dc6afc024164633145d"
metafile = true

[[files]]
file = "mods/biome-replacer.pw.toml"
hash = "7170c3cce8959cf23812283df3449750547e1cbc76ec118f1d78299ae78efa29"
metafile = true

[[files]]
file = "mods/bridging-mod.pw.toml"
hash = "c50696cd98b02ba03425574c7850443f5cba8e097af4b6ae1c8b42bd5316a8eb"
metafile = true

[[files]]
file = "mods/carved-wood.pw.toml"
hash = "b9a0507facfb51fcda94a7d9cfff8c43a590393d87edf5d8ecb541bce36977b5"
metafile = true

[[files]]
file = "mods/chunky.pw.toml"
hash = "1d5cc2b6dcfd1fc3adba4566b1c29b57ff1175316678c1f22e63cbc3e28a5ba0"
metafile = true

[[files]]
file = "mods/cloth-config.pw.toml"
hash = "75181b55e0407d1fca1e2f346c6501f919f5109545990ddfb66db9cd1b771f8a"
metafile = true

[[files]]
file = "mods/clutter-no-more.pw.toml"
hash = "eff3c5d7048e777f6efd57a2f78a56a2a84d9139ab9d213112d0913e46e31e49"
metafile = true

[[files]]
file = "mods/cobweb.pw.toml"
hash = "23f681379a3e647a59f0749d25f2ce0725d4afafeed41871c5c87f2658d13a72"
metafile = true

[[files]]
file = "mods/controlling.pw.toml"
hash = "65c8086d2ec3d39acc7bd36c7a0306ccc43b602b38fa07d13291bc478ef7dfff"
metafile = true

[[files]]
file = "mods/copycats.pw.toml"
hash = "e002fab16a9b9ef0a35844030339612a38d3c58b0b93e97a34eb43ddc9108be7"
metafile = true

[[files]]
file = "mods/create-bits-n-bobs.pw.toml"
hash = "c0210ae315fb7c8ddc5264af382afb2a456621609f03e91d160e25a9bd5e340b"
metafile = true

[[files]]
file = "mods/create-central-kitchen.pw.toml"
hash = "dbdb686363922b46666480726b8470cbb8a6ed8386c5c3f20ff6ac06b0654e67"
metafile = true

[[files]]
file = "mods/create-design-n-decor.pw.toml"
hash = "bc4ef8bd7d32506703dcc175a62a12766addc393434ddbe8d17f01b071701943"
metafile = true

[[files]]
file = "mods/create-dragons-plus.pw.toml"
hash = "ed5a88a8d97fe38cca25a42aa1ffcaf51f8f84535f872a9446eff96b92b5722a"
metafile = true

[[files]]
file = "mods/create-enchantment-industry.pw.toml"
hash = "9f3bd10fad13a1024513590b53976f0c7c9eb404727b3d08fe87ebbf451bcd04"
metafile = true

[[files]]
file = "mods/create.pw.toml"
hash = "d6043c928c34ce1f4ada544a49193f95c281665cf88d4931e73370ea02870bed"
metafile = true

[[files]]
file = "mods/creativecore.pw.toml"
hash = "4252858199f6d7854cd4612f8b345fe4486676f6e057d64d199239c05f9ae0a8"
metafile = true

[[files]]
file = "mods/curios.pw.toml"
hash = "36debf7653e95a855b4fedacc19027cf2e01960fc0b6d55ef2ffbffbcb455690"
metafile = true

[[files]]
file = "mods/dcintegration.pw.toml"
hash = "a832de493f31251061455e1a473471d115ff875400ddeae78e35ae8c7868c3c1"
metafile = true

[[files]]
file = "mods/emi.pw.toml"
hash = "d3c9b48d7caa2ed964e5d1a4dab1da5655c63f0a7e4a59231c4369be7ffc30e1"
metafile = true

[[files]]
file = "mods/entityculling.pw.toml"
hash = "77d59ac7bb40c00032d68d45d777e8c1c0dc22596afe0c84572104a67dabb1d5"
metafile = true

[[files]]
file = "mods/exposure.pw.toml"
hash = "c22010071589a36869a478fda1eae893adcc15fc9ab9996a195cc6f54333891b"
metafile = true

[[files]]
file = "mods/extended-wrenches.pw.toml"
hash = "6bb119edbf8141abafaea3a69027942547de739bd69b2107a6b9d2e7dc6e2ce7"
metafile = true

[[files]]
file = "mods/farmers-delight.pw.toml"
hash = "44abae510395f12f9ea97b8296b2f72e25f18b9f3f2cc0ee42c0d9afd73fe0b3"
metafile = true

[[files]]
file = "mods/ferrite-core.pw.toml"
hash = "05d96d5b17399f048469ff4b44451eb8d99cc7a2a075ff55718c397cb508b0c2"
metafile = true

[[files]]
file = "mods/figura.pw.toml"
hash = "19c09828ce6d394ec1d9906b1a6ff02998052274024182e83027c6e8eee9eb04"
metafile = true

[[files]]
file = "mods/flerovium.pw.toml"
hash = "63edd38d9bb8987b5b276f337aa915c07100bdcbf1c2c41ddc510fac3ad82cf2"
metafile = true

[[files]]
file = "mods/flw-vanillin.pw.toml"
hash = "cbcaf4a18e45757f17d4a4f36469f879ae024a9fe58b8129d8a42d0faaeada22"
metafile = true

[[files]]
file = "mods/fog.pw.toml"
hash = "3a90f022d0ac776053cfb3a74de2f5df7b1a1388c1fb223ea7396a052843989f"
metafile = true

[[files]]
file = "mods/geckolib.pw.toml"
hash = "960fb33c17aca9c635f99009c1f16d75c312d043e302a599f6ce8040452079e6"
metafile = true

[[files]]
file = "mods/glitchcore.pw.toml"
hash = "dbd756dd9bb17e6ecebcf2d7052a67a2da1c7dd378bc2089bc154916080fe031"
metafile = true

[[files]]
file = "mods/harvest-with-ease.pw.toml"
hash = "1e5b320ad839b14df9754644d36a10bc745bf165da797b9b195136ee6b1f06a7"
metafile = true

[[files]]
file = "mods/jade-addons-forge.pw.toml"
hash = "8cd8400cb4e2c5ba60c8a359a7b6ff501078d2056eab0aba7f6b0ac77b7a0694"
metafile = true

[[files]]
file = "mods/jade.pw.toml"
hash = "e7d3f7e0472ba9a3ef946fa5defcb157e4126636e603c2306d4ad6065936d5e2"
metafile = true

[[files]]
file = "mods/jolly-core.pw.toml"
hash = "f61968eb25d0b51f118294252e529c6413fdc2794ae9ed3a27fb9e40d9e671ad"
metafile = true

[[files]]
file = "mods/kiwi.pw.toml"
hash = "caa948011054593b7452cfc4fa7276ff61748770285fd6b7ee5078816eed043b"
metafile = true

[[files]]
file = "mods/ksyxis.pw.toml"
hash = "8c6b70c5687944d95858a7da9311a268725bc613e1d0f10dae4687faf9fb7ad5"
metafile = true

[[files]]
file = "mods/lambdynamiclights.pw.toml"
hash = "502d4ba2ca8c7f6f52830cfc43fc12b567023266f2b557ee2b8eea737b58f8ea"
metafile = true

[[files]]
file = "mods/lithium.pw.toml"
hash = "7b8e8af83e8583adc91b2d859e5355f1bd0516a346d2584b8b01c004467d18af"
metafile = true

[[files]]
file = "mods/lithostitched.pw.toml"
hash = "92034e181912b22e6fad965c22dec692480663961cc5f3c2252e1b792fce0081"
metafile = true

[[files]]
file = "mods/moonlight.pw.toml"
hash = "56f90779687daa9101ae4dc2730a3b44b07ed3a5113eb4f4b41e36143b297f56"
metafile = true

[[files]]
file = "mods/mouse-tweaks.pw.toml"
hash = "6bc414cc0f2d4c078fe83f384d786343f701f371d657c5279b5b0df1595804bd"
metafile = true

[[files]]
file = "mods/mru.pw.toml"
hash = "42805ef7e224873873d190b0363f2a53dae02530553574f29fab92e258bc0470"
metafile = true

[[files]]
file = "mods/notenoughrecipebook.pw.toml"
hash = "6df80014ec12832c5627e60f7c916e0cb8a9d8dbb3f7c4ff863de3a6e39957aa"
metafile = true

[[files]]
file = "mods/octo-lib.pw.toml"
hash = "a52c2b505827a549dfabebd6586591910fcf6e1a62dbb27604aacc96d412d5e4"
metafile = true

[[files]]
file = "mods/opticmanager.pw.toml"
hash = "df7361752c7becf56a82345e9b084ce824367a109166e11190dd6ad4f66cca0f"
metafile = true

[[files]]
file = "mods/owo-lib.pw.toml"
hash = "46831c04077a06df823bcd0f254833a90a9a9ccc78f5069f4b4c27fa301ac0cf"
metafile = true

[[files]]
file = "mods/particle-rain.pw.toml"
hash = "95886f73121a490ab360dac8e99f260fb0346048e86475c658ed44ddd399f09e"
metafile = true

[[files]]
file = "mods/pause-day-cycle.pw.toml"
hash = "a8bb27c7a03233f164d48537fffc20160c7166c7fba72e79780a36ca40356549"
metafile = true

[[files]]
file = "mods/paxi.pw.toml"
hash = "215d597764d5c5db89e700fc3495b72dc0a7f09c975de19dc8c580bde3469a5e"
metafile = true

[[files]]
file = "mods/platform.pw.toml"
hash = "ce6e210ac63b92f3255c4896d116f35b0af8c57a1f84dab744d939535ea528ce"
metafile = true

[[files]]
file = "mods/quick-pack.pw.toml"
hash = "884325ab8ea09fc82883a3e27c340c3e978c167420977e89166061b31338a490"
metafile = true

[[files]]
file = "mods/raised.pw.toml"
hash = "5da8dcc00f7619473593f584dafe15e0ff5c8b6cd5b7267236d77df4ba57a3cc"
metafile = true

[[files]]
file = "mods/rapid-leaf-decay.pw.toml"
hash = "748402afa804b7e3da2208009a0caa4c9dea415a098776fdfaba00148d2e6d5f"
metafile = true

[[files]]
file = "mods/satchels.pw.toml"
hash = "2eced12c4bc6572f1b718ab6b090df8ca754003747fecbc753ae2010217fdd57"
metafile = true

[[files]]
file = "mods/searchables.pw.toml"
hash = "ce9ddada6ffd55a512149cc474c6a453281a997a5fdf1b7b4a2cc73f875e704a"
metafile = true

[[files]]
file = "mods/serene-seasons.pw.toml"
hash = "73b1e4f6608fcd396acc3e4e7aa753d314c8810ef4caf831ed93d9932d93f896"
metafile = true

[[files]]
file = "mods/simple-voice-chat.pw.toml"
hash = "97b2aef4e58e020a28122feea6dfcef731581cb12094047aae8c1e6077c54e75"
metafile = true

[[files]]
file = "mods/snow-real-magic.pw.toml"
hash = "a1deef8071fb83a13df63c289576813b82f0687eebda9b48b7667620d5d45103"
metafile = true

[[files]]
file = "mods/snow-sniffer.pw.toml"
hash = "87540c0d6ab0668d93a31b77eb794c76acee411475365a148eb1225e029d5a0d"
metafile = true

[[files]]
file = "mods/snow-under-trees.pw.toml"
hash = "82aedef3c457ffe51e27a4153aaf73ef7c073b87059a021495af487e41ed2e99"
metafile = true

[[files]]
file = "mods/snowy-spirit.pw.toml"
hash = "69be2f0d320f3b53aec597f2b27d477cdbfa902ea2cd1002b0f9c49bf41c2ba6"
metafile = true

[[files]]
file = "mods/sodium.pw.toml"
hash = "0281ed9713f3141bdac363056a791845510e14761ea65b4b2813cf96d664b20a"
metafile = true

[[files]]
file = "mods/supplementaries.pw.toml"
hash = "ee4d30e45f196b78932dc795c211a9214d033397d79ed27ca05dbb82b02c2775"
metafile = true

[[files]]
file = "mods/terrablender.pw.toml"
hash = "15962183bec2468058c70e87aa32e902a08489b0f86741088cdc9aa958ba4931"
metafile = true

[[files]]
file = "mods/tmrv.pw.toml"
hash = "9a2c112447329f1daea6cda77d68d3cdf7f292ae9e72f69adbfc18cb18ab1eeb"
metafile = true

[[files]]
file = "mods/vanillabackport.pw.toml"
hash = "b278c479cc1d50ffbcf27e3514bcdb0995471eb11e2335c54255edc459b3462e"
metafile = true

[[files]]
file = "mods/xaeros-minimap.pw.toml"
hash = "9d76c3683cfea5c5976823a000eacc9944db9f097894356d2a029cf36642ffa4"
metafile = true

[[files]]
file = "mods/xaeros-world-map.pw.toml"
hash = "9b8940ac83dde84cfc59860c6544a4b1194e635786c26bd47dc15eee79e63598"
metafile = true

[[files]]
file = "mods/yacl.pw.toml"
hash = "9a89a97f142873b9ab62d2c7c807ac22e6f16c828282052b416a6f3f7f785a48"
metafile = true

[[files]]
file = "mods/yosbr-neo.pw.toml"
hash = "253d02e33da60a75621cd221c38dde0b6aac3f9965f780dd52094fc1c39eed67"
metafile = true

[[files]]
file = "mods/yungs-api.pw.toml"
hash = "d9c0c9209bac0b693af2a7c1e47ffb28d366bad19c91df31dc6d345fa75250a1"
metafile = true

[[files]]
file = "mods/yungs-better-dungeons.pw.toml"
hash = "1496ffa30020676979e65921b91e583a2fdc77e50001e2ed55f99edf1a0ae880"
metafile = true

[[files]]
file = "mods/yungs-cave-biomes.pw.toml"
hash = "5a334201feff0fb2f76d486399f47d0ce5b5818c284fea895706c92bb2119470"
metafile = true

[[files]]
file = "mods/yungs-extras.pw.toml"
hash = "cfb7ce4c2b00cedd2e61f7d345b824d6bcc1471021668d2319ee2e4079108639"
metafile = true

[[files]]
file = "mods/yungs-menu-tweaks.pw.toml"
hash = "a0d823abe0f59e943433820b7564d69cc453aa64b0ca472d242bd92dcb7cb215"
metafile = true
