name = "The Jolly Season"
author = "Vercte"
version = "1.4.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "142ae5181bef64366ac920831fb02370d8ab97fb584eb9cdc057faf8eeacbd75"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.216"
