name = "The Jolly Season"
author = "Vercte"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d25f62ffb5e4abbcba2a65f9c940aa29d23968786f95275a9c606634de43d46c"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.216"
