name = "The Jolly Season"
author = "Vercte"
version = "1.5.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2d99a75352edd07adfa894ae5ea23f4d15cc45f6f3828c55cb4499a7539d7f6f"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.216"

[options]
acceptable-game-versions = ["1.21"]
