name = "The Jolly Season"
author = "Vercte"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a6e0bdbc065db09cf5e1a75ffe3cd9acfd4ca5799a2049d0bda2a69f224a9d30"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.216"
