name = "The Jolly Season"
author = "Vercte"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "89bf365f7b5aac0a9d7ede0568d2bded8a4fb0ad3553489bb4b730f3c4010419"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.216"
