name = "The Jolly Season"
author = "Vercte"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "14dd94dbb0b82b6486c38a13402fcd341597c53bdd98dba2b018b2aaac19fedd"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.216"
